# Generated by Django 5.0.3 on 2024-04-07 04:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=100)),
                ('hours_spent', models.FloatField()),
                ('day_of_week', models.CharField(max_length=9)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoalsDreams',
            fields=[
                ('goal_id', models.AutoField(primary_key=True, serialize=False)),
                ('goaltitle', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('achieved', models.BooleanField(default=False)),
                ('hours_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('hours_required', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('connected_emails', models.TextField(default='')),
                ('incentive', models.TextField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
