# Generated by Django 5.0.3 on 2024-04-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeapp', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
    ]
