# Generated by Django 5.0.3 on 2024-04-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeapp', '0002_goalsdreams_achieved_goalsdreams_date_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalsdreams',
            name='goal',
        ),
        migrations.AddField(
            model_name='goalsdreams',
            name='connected_emails',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='goalsdreams',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='goalsdreams',
            name='goaltitle',
            field=models.TextField(default=''),
        ),
    ]
