// src/store/dummyData.js
export const dummyGoals = [
    {
        goal_id: 1,
        user: 1,
        goaltitle: "My First Goal",
        description: "Hello, this is my first goal with index.",
        achieved: true,
        hours_spent: "0.00",
        hours_required: "3.00",
        date_time: "2024-04-07T04:15:14Z",
        connected_emails: "email@example.com",
        incentive: "Complete this for a reward",
    },
    {
        goal_id: 2,
        user: 1,
        goaltitle: "Learn Redux",
        description: "Understand the basics of Redux for state management.",
        achieved: false,
        hours_spent: "1.50",
        hours_required: "5.00",
        date_time: "2024-05-01T10:00:00Z",
        connected_emails: "developer@example.com",
        incentive: "Unlock advanced state management techniques.",
    },
    {
        goal_id: 3,
        user: 1,
        goaltitle: "Complete Project X",
        description: "Finalize all pending tasks in Project X.",
        achieved: false,
        hours_spent: "20.00",
        hours_required: "25.00",
        date_time: "2024-05-15T12:00:00Z",
        connected_emails: "project.team@example.com",
        incentive: "Project completion bonus.",
    },
    {
        goal_id: 4,
        user: 1,
        goaltitle: "Exercise Regularly",
        description: "Establish a consistent exercise routine.",
        achieved: true,
        hours_spent: "15.00",
        hours_required: "12.00",
        date_time: "2024-04-20T07:00:00Z",
        connected_emails: "gym@example.com",
        incentive: "Improved health and wellness.",
    },
    {
        goal_id: 5,
        user: 1,
        goaltitle: "Read 12 Books This Year",
        description: "Expand knowledge and relaxation by reading more.",
        achieved: false,
        hours_spent: "30.00",
        hours_required: "48.00",
        date_time: "2024-12-31T23:59:59Z",
        connected_emails: "book.club@example.com",
        incentive: "Join the year-end book club discussion.",
    },
    // Add as many goals as needed for testing
];

export default dummyGoals;
